//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alsolos.Photo.Renamer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alsolos.Photo.Renamer.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Area_Execute {
            get {
                return ResourceManager.GetString("Area_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string Area_FileList {
            get {
                return ResourceManager.GetString("Area_FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Area_Parameter {
            get {
                return ResourceManager.GetString("Area_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Area_Preview {
            get {
                return ResourceManager.GetString("Area_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Button_Execute {
            get {
                return ResourceManager.GetString("Button_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Files.
        /// </summary>
        public static string Button_OpenFiles {
            get {
                return ResourceManager.GetString("Button_OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Folder.
        /// </summary>
        public static string Button_OpenFolder {
            get {
                return ResourceManager.GetString("Button_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files.
        /// </summary>
        public static string FileListCountMany {
            get {
                return ResourceManager.GetString("FileListCountMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 file.
        /// </summary>
        public static string FileListCountSingle {
            get {
                return ResourceManager.GetString("FileListCountSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Name Part.
        /// </summary>
        public static string Param_ConstantName {
            get {
                return ResourceManager.GetString("Param_ConstantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Days.
        /// </summary>
        public static string Param_OffsetDays {
            get {
                return ResourceManager.GetString("Param_OffsetDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Hours.
        /// </summary>
        public static string Param_OffsetHours {
            get {
                return ResourceManager.GetString("Param_OffsetHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Minutes.
        /// </summary>
        public static string Param_OffsetMinutes {
            get {
                return ResourceManager.GetString("Param_OffsetMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Seconds.
        /// </summary>
        public static string Param_OffsetSeconds {
            get {
                return ResourceManager.GetString("Param_OffsetSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Time.
        /// </summary>
        public static string Preview_AdjustedTime {
            get {
                return ResourceManager.GetString("Preview_AdjustedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time from File.
        /// </summary>
        public static string Preview_CreatedTime {
            get {
                return ResourceManager.GetString("Preview_CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Name.
        /// </summary>
        public static string Preview_FileName {
            get {
                return ResourceManager.GetString("Preview_FileName", resourceCulture);
            }
        }
    }
}
